name: example
description: An example web application with Finch package dart.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_web_compilers: 
  test:
  dart_dev: 
  build_runner:
  json_serializable:

dependencies:
  finch: #^1.0.3 
    path: ../
  watcher:

finch:
  run: ./lib/app.dart
  serve: ./lib/serve.dart
  languages_path: ./lib/languages
  widgets_path: ./lib/widgets
  mysql_migrate:
    path: ./lib/mysql/migrations
  sqlite_migrate:
    path: ./lib/sqlite/migrations